name: Remove site preview for PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group:  preview-${{ github.event.number }}

jobs:
  remove-preview:
    if: ${{ ! github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ vars.PREVIEW_REPOSITORY }}
          token: ${{ secrets.PREVIEW_TOKEN }}

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm -r ${{ github.event.number }}
          git commit -m "remove preview for PR #${{ github.event.number }}"
          git push
